// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADm_scTXk7oTh39uFtKEuDlnqvP4OqoqA',
    appId: '1:840309410876:web:ba4d4ccb832f42b677c739',
    messagingSenderId: '840309410876',
    projectId: 'callog-30758',
    authDomain: 'callog-30758.firebaseapp.com',
    storageBucket: 'callog-30758.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADm_scTXk7oTh39uFtKEuDlnqvP4OqoqA',
    appId: '1:840309410876:android:ba4d4ccb832f42b677c739',
    messagingSenderId: '840309410876',
    projectId: 'callog-30758',
    storageBucket: 'callog-30758.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADm_scTXk7oTh39uFtKEuDlnqvP4OqoqA',
    appId: '1:840309410876:ios:ba4d4ccb832f42b677c739',
    messagingSenderId: '840309410876',
    projectId: 'callog-30758',
    storageBucket: 'callog-30758.firebasestorage.app',
    iosBundleId: 'com.callog.mobile-app',
  );
}
